name: Ubuntu Workflow for Codecov checks
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: apt-get install bedtools
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install the main package
        run: pip install -e .
      - name: Run tests and collect coverage
        run: |
          pip install coverage
          coverage run tests/test_main.py
          coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.MY_CODECOV_CODECOV }} # not required when make public
